name: Ubuntu 22.04 with undefined sanitizer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu-build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        shared: [ON, OFF]
        cxx: [clang++-14]
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: cmake -D ADA_SANITIZE_UNDEFINED=ON -DBUILD_SHARED_LIBS=${{matrix.shared}} -B build
        env:
          CXX: ${{matrix.cxx}}
      - name: Build
        run: cmake --build build
      - name: Test
        run: ctest --output-on-failure  --test-dir build
